quarkus:
  http:
    port: 8080
  swagger-ui:
    always-include: true
    path: /api
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}/${FANTASY_F1_DB:fantasy_f1}
    driver: org.postgresql.Driver
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    max-size: 8
    min-size: 2
  hibernate-orm:
    physical-naming-strategy: com.aklysoft.fantasyf1.service.core.orm.SnakeCaseNamingStrategy
    database:
      generation: drop-and-create
    sql-load-script: import.sql
    log:
      sql: false
  container-image:
#    group: aklysoft
    name: fantasy-f1-service
    tag: 1.0.0-SNAPSHOT
  kubernetes:
    service-type: load-balancer

app:
  download-limit: 50
  show-stacktrace: true

"%test":
  quarkus:
    datasource:
      url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}/${FANTASY_F1_TEST_DB:fantasy_f1_test}
    hibernate-orm:
      database:
        generation: drop-and-create
      sql-load-script: import_test.sql

"%prod":
  quarkus:
    hibernate-orm:
      sql-load-script: import.sql # temporarily
  app:
    show-stacktrace: false
