INSERT INTO FANTASY_SERIES(ID, NAME) VALUES ('f1', 'Formula 1');
INSERT INTO FANTASY_SERIES(ID, NAME) VALUES ('fe', 'Formula E');

INSERT INTO FANTASY_DEFINITIONS(SERIES, SEASON, NEXT_RACE) VALUES ('f1', 2019, 1);

INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR, SORT_ORDER) VALUES ('ENGINE', 'Engine', TRUE, 3);
INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR, SORT_ORDER) VALUES ('BODY', 'Body', TRUE, 4);
INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR, SORT_ORDER) VALUES ('STAFF', 'Staff', TRUE, 5);
INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR, SORT_ORDER) VALUES ('DRIVER_1', 'Driver 1', FALSE, 1);
INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR, SORT_ORDER) VALUES ('DRIVER_2', 'Driver 2', FALSE, 2);


INSERT INTO PLAYERS (USER_NAME, FIRST_NAME, LAST_NAME, POINTS, CREATED) VALUES ('user', 'User', 'Test', 100, current_timestamp);
INSERT INTO PLAYERS (USER_NAME, FIRST_NAME, LAST_NAME, POINTS, CREATED) VALUES ('sziszo', 'Szilard', 'Antal', 100, current_timestamp);
INSERT INTO PLAYERS (USER_NAME, FIRST_NAME, LAST_NAME, POINTS, CREATED) VALUES ('john', 'John', 'Doe', 10, current_timestamp);
INSERT INTO PLAYERS (USER_NAME, FIRST_NAME, LAST_NAME, POINTS, CREATED) VALUES ('charlie', 'Charlie', 'Adam', 50, current_timestamp );
