INSERT INTO FANTASY_SERIES(ID, NAME) VALUES ('f1', 'Formula 1');
INSERT INTO FANTASY_SERIES(ID, NAME) VALUES ('fe', 'Formula E');

INSERT INTO FANTASY_DEFINITIONS(SERIES, SEASON, NEXT_RACE) VALUES ('f1', 2019, 1);

INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR) VALUES ('ENGINE', 'Engine', TRUE);
INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR) VALUES ('BODY', 'Body', TRUE);
INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR) VALUES ('STAFF', 'Staff', TRUE);
INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR) VALUES ('DRIVER_1', 'Driver 1', FALSE);
INSERT INTO FANTASY_TEAM_MEMBER_CATEGORIES(ID, NAME, IS_CONSTRUCTOR) VALUES ('DRIVER_2', 'Driver 2', FALSE);

INSERT INTO PLAYERS (USER_NAME, FIRST_NAME, LAST_NAME, POINTS, CREATED) VALUES ('test', 'Test', 'Test', 100, current_timestamp);
INSERT INTO PLAYERS (USER_NAME, FIRST_NAME, LAST_NAME, POINTS, CREATED) VALUES ('user', 'User', 'User', 100, current_timestamp);
INSERT INTO PLAYERS (USER_NAME, FIRST_NAME, LAST_NAME, POINTS, CREATED) VALUES ('john', 'John', 'Doe', 10, current_timestamp);

